sudo:
  required

language:
  minimal

install:
  - ./.travis/install.sh

before_script:
  - ./.travis/verify.sh

script:
  - ./.travis/build.sh

deploy:
  provider: script
  script: ./.travis/deploy.sh
