dist:
  xenial

language:
  node_js

node_js:
  lts/*

install:
  make install

before_script:
  make production

script:
  make lint

before_deploy:
  - make minify
  - cp -f dist/vault.html dist/404.html # TEMP: https://github.com/travis-ci/dpl/issues/912

deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  fqdn: vault.ashenm.ml

after_deploy:
  make purge

notifications:
  slack:
    secure: SLfHbLPYkxXmIZntD8zWIhzxDHc6o0v1uwyo3iAQbA8fz8hbvVmd19O846FUAMu4mUaUu0I2QHHSvrfOjlvsr4PCYwTlgg0MDz6FvbeOQDiA1QdyXqEzUIzR7zOBu4y6PCTdckbHPMmey0QnVTDyqKFG1tBmmbHq+MqBJlRi1EiJMrHtunBo4/QojwDRAL5FBKx4dnoO+Bi4CgQtmde/IlbVUd18encrRFidbsNFN3fx02VFGe4JIfjob+i6YFr9ytJa6NHD4qjFCvZE+U8VWPgozzFyixmesSdAauzP/zxr2RtlyN3Mih9X/36tJFKM48WXJwKC1Pn1IcaApjok6tkN3nRDlMiJXb1W8lrzKsHielG1g0smgKGShpevSrJE3D2PPooaQYy4FghB6HCC4omivDup4JV+NRNwQymRjD52/JMRolW7UWcTPx+/AJdhCIPRJhgCqRzWiIkJYe/Cw7QMcKxIb/8Rpj8SlTKKjuYDFZ343P0WcV4XY5HVSfyiQAinHlKYpSsV3kta+Tzy/g3JJusv4kyFIfHjML9y+fCL442PGjxF7FwZDUHZ/2ta/UKSye+ZgmUnXvEbatTEWcbr+wuq5UtnpJfEmaSzCohSRkK7s2S6l0pe4jBMglVbeC8WrMud9h7w4ADb84Ii3IaZSzak7Nfnc6nyJon5faU=
